"""SQLAlchemy 2.0 model — LucasRecommendationModel.

Maps to ``vitalia_lucas_recommendations`` table (base columns from 007_vitalia_initial_tables.py,
additions from 028_slice1_marketing_lucas_recommendations.py).

HIPAA-lite:
  - NO PHI: recommendations contain marketing metrics and budget advice only.
  - clinic_id: second scope filter (dual filter per hipaa-lite.md § Tenant isolation refuerzo).
  - rejected_by_user_id / approved_by_user_id: IAM user UUIDs (not patient IDs).

Lifecycle: OPEN → APPROVED (with 5-min undo window) | REJECTED | EXPIRED (cron)

downstream-regression-na: brand-local marketing infrastructure model
"""

from __future__ import annotations

from datetime import datetime
from uuid import UUID, uuid4

from luana_core_platform.domain.base_entity import Base
from sqlalchemy import DateTime, Index, Integer, SmallInteger, String, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func


class LucasRecommendationModel(Base):
    """A marketing recommendation generated by Lucas AI for a clinic.

    Lifecycle states (status column): open | approved | rejected | expired
    undo_until: 5-minute window after approval for undo (cron clears after)
    """

    __tablename__ = "vitalia_lucas_recommendations"

    id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True, default=uuid4)
    tenant_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), nullable=False, index=True)
    clinic_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), nullable=False, index=True)

    # Bowtie funnel stage: "attract" | "convert" | "retain"
    stage: Mapped[str] = mapped_column(String(32), nullable=False)

    # Recommendation classification (e.g. "increase_budget", "adjust_targeting")
    recommendation_kind: Mapped[str] = mapped_column(String(64), nullable=False)

    # User-facing content (no PHI)
    title: Mapped[str] = mapped_column(String(256), nullable=False)
    body: Mapped[str] = mapped_column(Text, nullable=False)

    # AI-generated rationale (metrics evidence, no patient data)
    rationale_json: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)

    # Sort order (higher = more urgent)
    priority: Mapped[int] = mapped_column(Integer, nullable=False, default=1)

    # Lifecycle: "open" | "approved" | "rejected" | "expired"
    status: Mapped[str] = mapped_column(String(32), nullable=False, default="open")

    # Expiry — cron marks OPEN recs as expired after this datetime
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    # Optional structured action (e.g. {"action": "increase_budget", "amount_cents": 5000})
    action_payload_json: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    # AI confidence percentage (0-100)
    confidence_pct: Mapped[int | None] = mapped_column(SmallInteger, nullable=True)

    # Human-readable projected impact (e.g. "+15% CTR estimated")
    projected_impact_text: Mapped[str | None] = mapped_column(String(256), nullable=True)

    # Approval tracking
    approved_by_user_id: Mapped[UUID | None] = mapped_column(PgUUID(as_uuid=True), nullable=True)
    approved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # 5-minute undo window after approval
    undo_until: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Rejection tracking
    rejected_by_user_id: Mapped[UUID | None] = mapped_column(PgUUID(as_uuid=True), nullable=True)
    rejected_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    reject_reason: Mapped[str | None] = mapped_column(String(64), nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    __table_args__ = (
        # For list_open_by_stage — filter OPEN recs by clinic + stage
        Index(
            "ix_vitalia_lucas_rec_clinic_stage_status",
            "tenant_id",
            "clinic_id",
            "stage",
            "status",
        ),
        # For list_pending_undo_expired — filter APPROVED recs with undo_until in past
        Index(
            "ix_vitalia_lucas_rec_approved_undo",
            "tenant_id",
            "clinic_id",
            "status",
            "undo_until",
        ),
    )
